-- ==========================================
-- 1. DATABASE & SCHEMA SETUP
-- ==========================================
CREATE DATABASE IF NOT EXISTS PHARMA_DB;
CREATE SCHEMA IF NOT EXISTS PHARMA_DB.PHARMA_SUPPLY_CHAIN;

USE DATABASE PHARMA_DB;
USE SCHEMA PHARMA_SUPPLY_CHAIN;

-- ==========================================
-- 2. CORE TABLES DDL (RAW DATA LAYER)
-- ==========================================
CREATE OR REPLACE TABLE INVENTORY_STATUS (
    Warehouse_ID STRING,
    Drug_ID STRING,
    Qty_On_Hand INT,
    Daily_Demand INT
);

CREATE OR REPLACE TABLE SUPPLIER_METRICS (
    Supplier_Name STRING,
    Drug_ID STRING,
    On_Time_Delivery_Rate FLOAT,
    Defect_Rate FLOAT
);

-- ==========================================
-- 3. MOCK DATA INJECTION
-- ==========================================
-- Sample of the 30 rows generated by CoCo CLI
INSERT INTO INVENTORY_STATUS (Warehouse_ID, Drug_ID, Qty_On_Hand, Daily_Demand) VALUES
('WH-101', 'DRG-001-PARACETAMOL', 450, 150),
('WH-102', 'DRG-001-PARACETAMOL', 3200, 200),
('WH-101', 'DRG-002-AMOXICILLIN', 1500, 300),
('WH-103', 'DRG-002-AMOXICILLIN', 200, 250),
('WH-104', 'DRG-003-IBUPROFEN', 5000, 400),
('WH-105', 'DRG-004-METFORMIN', 800, 100);

INSERT INTO SUPPLIER_METRICS (Supplier_Name, Drug_ID, On_Time_Delivery_Rate, Defect_Rate) VALUES
('PharmaCure Ltd', 'DRG-001-PARACETAMOL', 0.98, 0.010),
('MediSource Inc', 'DRG-001-PARACETAMOL', 0.85, 0.030),
('GenericHealth Co', 'DRG-002-AMOXICILLIN', 0.95, 0.005),
('BioGen Pharma', 'DRG-003-IBUPROFEN', 0.99, 0.003),
('Apex Generics', 'DRG-004-METFORMIN', 0.89, 0.025);

-- ==========================================
-- 4. GOVERNED SEMANTIC VIEWS (LOGIC LAYER)
-- ==========================================
-- View 1: Hardcodes the formula for "Days of Inventory" to prevent LLM hallucinations
CREATE OR REPLACE VIEW INVENTORY_HEALTH_VIEW AS 
SELECT 
    Warehouse_ID, 
    Drug_ID, 
    Qty_On_Hand, 
    Daily_Demand, 
    (Qty_On_Hand / NULLIF(Daily_Demand, 0)) AS Days_Of_Inventory 
FROM INVENTORY_STATUS;

-- View 2: Hardcodes the formula for "Supplier Trust Score"
CREATE OR REPLACE VIEW SUPPLIER_RELIABILITY_VIEW AS 
SELECT 
    Supplier_Name, 
    Drug_ID, 
    On_Time_Delivery_Rate, 
    Defect_Rate, 
    (On_Time_Delivery_Rate - Defect_Rate) AS Supplier_Trust_Score 
FROM SUPPLIER_METRICS;

-- ==========================================
-- 5. WORKFLOW AUTOMATION (ACTION LAYER)
-- ==========================================
-- Stored Procedure triggered by the Streamlit App to resolve stockouts
CREATE OR REPLACE PROCEDURE REBALANCE_INVENTORY(SOURCE_WH VARCHAR, DEST_WH VARCHAR, DRUG VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    -- Remove stock from source warehouse
    UPDATE INVENTORY_STATUS 
    SET Qty_On_Hand = Qty_On_Hand - 500 
    WHERE Warehouse_ID = :SOURCE_WH AND Drug_ID = :DRUG;
    
    -- Add stock to destination warehouse
    UPDATE INVENTORY_STATUS 
    SET Qty_On_Hand = Qty_On_Hand + 500 
    WHERE Warehouse_ID = :DEST_WH AND Drug_ID = :DRUG;
    
    RETURN 'Rebalance Successful';
END;
$$;
